using System;
using System.Collections.Generic;
using FluentAssertions;
using Xunit;

namespace UrlMapper.Tests
{
    public class FirstRound
    {
        private ISimpleStringParameterBuilder Builder => new SimpleStringParameterBuilder();

        [Theory(DisplayName = "ระบบสามารถสร้าง object ของ StringParameter ได้")]
        [InlineData("")]
        [InlineData(null)]
        [InlineData("something")]
        [InlineData("\"!#$%&'()*+,-.:;<=>?@[]^_`|~ \\")]
        [InlineData("http://hackathon.com")]
        [InlineData("http://hackathon.com/")]
        [InlineData("http://hackathon.com/none")]
        [InlineData("http://hackathon.com/none/")]
        [InlineData("http://hackathon.com/{username}")]
        [InlineData("http://hackathon.com/{user!name}")]
        [InlineData("http://hackathon.com/{user\"name}")]
        [InlineData("http://hackathon.com/{user#name}")]
        [InlineData("http://hackathon.com/{user$name}")]
        [InlineData("http://hackathon.com/{user%name}")]
        [InlineData("http://hackathon.com/{user&name}")]
        [InlineData("http://hackathon.com/{user'name}")]
        [InlineData("http://hackathon.com/{user(name}")]
        [InlineData("http://hackathon.com/{user)name}")]
        [InlineData("http://hackathon.com/{user*name}")]
        [InlineData("http://hackathon.com/{user+name}")]
        [InlineData("http://hackathon.com/{user,name}")]
        [InlineData("http://hackathon.com/{user-name}")]
        [InlineData("http://hackathon.com/{user.name}")]
        [InlineData("http://hackathon.com/{user/name}")]
        [InlineData("http://hackathon.com/{user:name}")]
        [InlineData("http://hackathon.com/{user;name}")]
        [InlineData("http://hackathon.com/{user<name}")]
        [InlineData("http://hackathon.com/{user=name}")]
        [InlineData("http://hackathon.com/{user>name}")]
        [InlineData("http://hackathon.com/{user?name}")]
        [InlineData("http://hackathon.com/{user@name}")]
        [InlineData("http://hackathon.com/{user[name}")]
        [InlineData("http://hackathon.com/{user\name}")]
        [InlineData("http://hackathon.com/{user]name}")]
        [InlineData("http://hackathon.com/{user^name}")]
        [InlineData("http://hackathon.com/{user_name}")]
        [InlineData("http://hackathon.com/{user`name}")]
        [InlineData("http://hackathon.com/{user|name}")]
        [InlineData("http://hackathon.com/{user~name}")]
        [InlineData("http://hackathon.com/{user name}")]
        [InlineData("http://hackathon.com/{username}/service")]
        [InlineData("http://hackathon.com/{user!name}/service")]
        [InlineData("http://hackathon.com/{user\"name}/service")]
        [InlineData("http://hackathon.com/{user#name}/service")]
        [InlineData("http://hackathon.com/{user$name}/service")]
        [InlineData("http://hackathon.com/{user%name}/service")]
        [InlineData("http://hackathon.com/{user&name}/service")]
        [InlineData("http://hackathon.com/{user'name}/service")]
        [InlineData("http://hackathon.com/{user(name}/service")]
        [InlineData("http://hackathon.com/{user)name}/service")]
        [InlineData("http://hackathon.com/{user*name}/service")]
        [InlineData("http://hackathon.com/{user+name}/service")]
        [InlineData("http://hackathon.com/{user,name}/service")]
        [InlineData("http://hackathon.com/{user-name}/service")]
        [InlineData("http://hackathon.com/{user.name}/service")]
        [InlineData("http://hackathon.com/{user/name}/service")]
        [InlineData("http://hackathon.com/{user:name}/service")]
        [InlineData("http://hackathon.com/{user;name}/service")]
        [InlineData("http://hackathon.com/{user<name}/service")]
        [InlineData("http://hackathon.com/{user=name}/service")]
        [InlineData("http://hackathon.com/{user>name}/service")]
        [InlineData("http://hackathon.com/{user?name}/service")]
        [InlineData("http://hackathon.com/{user@name}/service")]
        [InlineData("http://hackathon.com/{user[name}/service")]
        [InlineData("http://hackathon.com/{user\name}/service")]
        [InlineData("http://hackathon.com/{user]name}/service")]
        [InlineData("http://hackathon.com/{user^name}/service")]
        [InlineData("http://hackathon.com/{user_name}/service")]
        [InlineData("http://hackathon.com/{user`name}/service")]
        [InlineData("http://hackathon.com/{user|name}/service")]
        [InlineData("http://hackathon.com/{user~name}/service")]
        [InlineData("http://hackathon.com/{user name}/service")]
        [InlineData("http://hackathon.com/{username}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user!name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user\"name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user#name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user$name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user%name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user&name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user'name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user(name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user)name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user*name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user+name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user,name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user-name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user.name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user/name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user:name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user;name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user<name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user=name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user>name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user?name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user@name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user[name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user\name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user]name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user^name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user_name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user`name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user|name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user~name}/service/{service-id}")]
        [InlineData("http://hackathon.com/{user name}/service/{service-id}")]
        public void BuilderCanCreateSimpleStringParameterObjectCorrecylt(string pattern)
        {
            var sut = Builder;
            sut.Parse(pattern).Should().NotBeNull();
        }

        [Theory(DisplayName = "ระบบสามารถตรวจสอบการจับคู่ของ pattern ได้ถูกต้อง")]
        [InlineData(null, "", false)]
        [InlineData(null, null, false)]
        [InlineData("", "", true)]
        [InlineData("", null, false)]
        [InlineData(" ", " ", true)]
        [InlineData(" ", "", false)]
        [InlineData(" ", null, false)]
        [InlineData("http://hackathon.com", "http://hackathon.com", true)]
        [InlineData("http://hackathon.com", "http://hackathon.com/", true)]
        [InlineData("http://hackathon.com/", "http://hackathon.com", true)]
        [InlineData("http://hackathon.com/", "http://hackathon.com/", true)]
        [InlineData("http://hackathon.com/none", "http://hackathon.com/none", true)]
        [InlineData("http://hackathon.com/none", "http://hackathon.com/none/", true)]
        [InlineData("http://hackathon.com/none/", "http://hackathon.com/none", true)]
        [InlineData("http://hackathon.com/none/", "http://hackathon.com/none/", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com//", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com///", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com////", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test!123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test\"123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test#123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test$123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test%123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test&123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test'123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test(123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test)123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test*123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test+123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test,123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test-123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test.123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test/123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test:123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test;123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test<123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test=123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test>123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test?123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test@123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test[123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test\\123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test]123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test^123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test_123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test`123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test|123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test~123", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test 123", true)]

        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/aa", true)]

        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test!123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test\"123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test#123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test$123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test%123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test&123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test'123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test(123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test)123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test*123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test+123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test,123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test-123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test.123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test/123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test:123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test;123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test<123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test=123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test>123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test?123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test@123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test[123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test\\123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test]123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test^123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test_123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test`123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test|123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test~123aa", true)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test 123aa", true)]

        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test!123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test\"123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test#123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test$123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test%123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test&123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test'123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test(123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test)123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test*123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test+123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test,123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test-123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test.123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test/123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test:123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test;123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test<123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test=123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test>123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test?123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test@123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test[123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test\\123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test]123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test^123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test_123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test`123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test|123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test~123", false)]
        [InlineData("http://hackathon.com/{username}aa", "http://hackathon.com/test 123", false)]

        [InlineData("http://hackathon.com/{username}", "http://hackathon.com//none", true)]

        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test!123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test\"123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test#123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test$123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test%123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test&123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test'123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test(123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test)123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test*123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test+123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test,123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test-123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test.123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test/123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test:123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test;123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test<123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test=123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test>123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test?123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test@123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test[123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test\\123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test]123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test^123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test_123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test`123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test|123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test~123/none", true)]
        [InlineData("http://hackathon.com/{username}", "http://hackathon.com/test 123/none", true)]

        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com//none", true)]

        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test!123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test\"123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test#123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test$123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test%123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test&123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test'123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test(123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test)123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test*123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test+123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test,123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test-123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test.123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test/123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test:123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test;123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test<123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test=123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test>123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test?123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test@123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test[123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test\\123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test]123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test^123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test_123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test`123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test|123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test~123/none", true)]
        [InlineData("http://hackathon.com/{username}/none", "http://hackathon.com/test 123/none", true)]

        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/aa/none", true)]

        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test!123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test\"123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test#123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test$123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test%123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test&123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test'123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test(123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test)123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test*123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test+123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test,123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test-123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test.123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test/123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test:123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test;123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test<123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test=123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test>123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test?123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test@123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test[123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test\\123/none", true)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test]123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test^123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test_123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test`123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test|123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test~123/none", false)]
        [InlineData("http://hackathon.com/{username}aa/none", "http://hackathon.com/test 123/none", false)]

        [InlineData("http://hackathon.com/{username}/service/{username}", "http://hackathon.com/test123/service/svid456", true)]

        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test!123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test\"123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test#123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test$123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test%123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test&123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test'123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test(123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test)123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test*123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test+123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test,123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test-123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test.123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test/123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test:123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test;123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test<123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test=123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test>123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test?123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test@123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test[123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test\\123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test]123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test^123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test_123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test`123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test|123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test~123/service/svid456", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test 123/service/svid456", true)]

        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test!123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test\"123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test#123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test$123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test%123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test&123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test'123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test(123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test)123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test*123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test+123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test,123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test-123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test.123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test/123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test:123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test;123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test<123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test=123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test>123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test?123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test@123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test[123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test\\123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test]123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test^123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test_123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test`123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test|123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test~123/customer/cid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}", "http://hackathon.com/test 123/customer/cid456", false)]

        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test!123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test\"123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test#123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test$123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test%123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test&123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test'123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test(123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test)123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test*123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test+123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test,123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test-123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test.123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test/123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test:123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test;123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test<123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test=123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test>123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test?123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test@123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test[123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test\\123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test]123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test^123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test_123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test`123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test|123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test~123/service/svid456aa", true)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test 123/service/svid456aa", true)]

        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test!123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test\"123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test#123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test$123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test%123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test&123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test'123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test(123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test)123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test*123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test+123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test,123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test-123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test.123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test/123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test:123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test;123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test<123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test=123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test>123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test?123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test@123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test[123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test\\123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test]123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test^123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test_123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test`123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test|123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test~123/service/svid456", false)]
        [InlineData("http://hackathon.com/{username}/service/{service-id}aa", "http://hackathon.com/test 123/service/svid456", false)]
        public void ValidateMatched(string pattern, string url, bool expectedResult)
        {
            var builder = Builder;
            var sut = builder.Parse(pattern);
            sut.Should().NotBeNull();
            sut.IsMatched(url).Should().Be(expectedResult);
        }

        [Theory(DisplayName = "ระบบสามารถทำการแยกข้อมูลออกจาก url ที่ส่งเข้ามาได้ถูกต้อง")]
        [InlineData("https://mana.com/linkto/{link-id}", "https://mana.com/linkto/A2348", "{link-id}", "A2348")]
        [InlineData("http://google.com/?s={keyword}", "http://google.com/?s=Xamarin", "{keyword}", "Xamarin")]
        [InlineData("https://mana.com/app/{app-id}/services/{service-id}", "https://mana.com/app/di394/services/878", "{app-id},{service-id}", "di394,878")]
        [InlineData("https://mana.com/nana/{app/-id}/services/{service-id}", "https://mana.com/nana/di394/services/services/878", "{app/-id},{service-id}", "di394,services/878")]
        public void ValidateExtractVariables(string pattern, string url, string keys, string values)
        {
            var builder = Builder;
            var sut = builder.Parse(pattern);

            var expectedDic = new Dictionary<string, string>();
            var expectedKeys = keys.Split(',', StringSplitOptions.RemoveEmptyEntries);
            var expectedValues = values.Split(',', StringSplitOptions.RemoveEmptyEntries);

            for (int elementIndex = 0; elementIndex < expectedKeys.Length; elementIndex++)
                expectedDic.Add(expectedKeys[elementIndex], expectedValues[elementIndex]);

            var actual = new Dictionary<string, string>();
            var isMatch = sut.IsMatched(url);
            sut.ExtractVariables(url, actual);
            actual.Should().NotBeNull().And.BeEquivalentTo(expectedDic);
        }
    }
}
